### ISSUE TITLE
error in favoritebusinesses query 

### ISSUE THREAD

**Issue by BhaskaranR** [DevanB/graphql-binding-yelp#1]
trying to understand the yelp example. favoritebusinesses gives me this error.  any help how to fix this?

Syntax Error GraphQL request (2:313) Expected Name, found }\n\n1: query ($_term: String, $_location: String, $_country: String, $_offset: Int, $_limit: Int, $_sort_by: String, $_locale: String, $_longitude: Float, $_latitude: Float, $_categories: String, $_open_now: Boolean, $_open_at: Int, $_price: String, $_attributes: [String], $_radius: Float) {\n2:   search(term: $_term, location: $_location, country: $_country, offset: $_offset, limit: $_limit, sort_by: $_sort_by, locale: $_locale, longitude: $_longitude, latitude: $_latitude, categories: $_categories, open_now: $_open_now, open_at: $_open_at, price: $_price, attributes: $_attributes, radius: $_radius) {}\n       

other queries work just fine

**Comment by BhaskaranR** [comment]
the return type for favoritebusinesses should be businesses instead of business.

**Comment by DevanB** [comment]
Thanks for pointing that out! I’ve updated the example.
